### ISSUE TITLE
Clicking on refresh icon causes the value to disappear

### ISSUE THREAD

**Issue by mzgreen** [Polidea/Cockpit#100]
**Library version**
Version of Cockpit the issue occurs in: `3.0.0`.

**To reproduce**
1. Yaml file:
```
appVersion:
  type: read_only
  description: "Version"
  group: "General"
```

2. In `Activity.onCreate` set the value like `Cockpit.setAppVersion(BuildConfig.VERSION_NAME)`.
3. Open Cockpit menu and click refresh icon in the top right corner.
4. Observe disappearing app version value.

**Expected behavior**
Values should not disappear when clicking refresh.

**Actual behavior**
Values disappear when clicking refresh.

**Device details**
Tested on Android 5.0, 8.0 and 9.0
